#BNF+IAT 1.0 UTF-8;
!grammar sixshot;

!slot <person>;//人称、称谓
!slot <chat>;

!slot <poems>;
!slot <poemcmd>;

!slot <numbers>;// 算数
!slot <caculatecmd>;
!slot <caculateresult>;

!slot <motionparticle>;// 运动
!slot <motiondirection>;
!slot <motionverb>;
!slot <motionstop>;


!start <rules>;
<rules>:

[<person>]<chat> //聊天
|[<poemcmd>]<poems> //诗歌、儿歌
|<numbers><caculatecmd><numbers><caculateresult>
|<motionparticle><motiondirection>[<motiondirection>]
|<motionstop>
;


// poem
<poemcmd>:背首|背个|背|背一个;
<poems>:登鹳雀楼|黄鹤楼|锄禾|小老鼠|一只小老鼠|鹅鹅鹅|咏鹅;

// chat
<person>:你;
<chat>:几岁|多大|叫什么|叫什么名字|属啥|属什么|真笨|真棒;

// caculate
<caculatecmd>:加|加上|减|减去|乘|乘以|除|除以;
<caculateresult>:得|等于;
<numbers>:1|2|3|4|5|6|7|8|9|10|11|12|13|14|15|16|17|18|19|20|21|22|23|24|25|26|27|28|29|30|31|32|33|34|35|36|37|38|39|40|41|42|43|44|45|46|47|48|49|50|51|52|53|54|55|56|57|58|59|60|61|62|63|64|65|66|67|68|69|70|71|72|73|74|75|76|77|78|79|80|81|82|83|84|85|86|87|88|89|90|91|92|93|94|95|96|97|98|99|100;

//motion
<motionparticle>:往|向;
<motiondirection>:前|后|左|右;
<motionverb>:走;
<motionstop>:停|停下|停下来;